[package]
name = "hyprhook-mouse-move"
version = "0.1.0"
edition = "2024"

[dependencies]
fork = "0.2.0"
mimalloc = "0.1.46"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
sysinfo = "0.35.2"

[profile.release]
debug = true
codegen-units = 1
lto = true
